#!/usr/bin/env python3

import sys
import os
from google.protobuf.descriptor_pb2 import FileDescriptorProto, FieldDescriptorProto
from google.protobuf.message import DecodeError


def is_valid_filename(filename):
    charset = 'abcdefghijklmnopqrstuvwxyz0123456789-_/$,.[]()'
    return all(char in charset for char in filename.lower())


def decode_varint128(stream):
    bits = ''
    count = 0
    for stream_byte in stream:
        count += 1
        raw_byte = stream_byte if isinstance(stream_byte, int) else ord(stream_byte)
        bits += bin(raw_byte & 0x7F)[2:].rjust(7, '0')
        if (raw_byte & 0x80) != 0x80:
            break
    return int(bits, 2), count


def render_type(field_type, package):
    nodes = field_type.split('.')
    nodes_ = package.split('.')
    for i in range(len(nodes)):
        if i < len(nodes_) and nodes[i] != nodes_[i]:
            return '.'.join(nodes[i:])
        elif i >= len(nodes_):
            return '.'.join(nodes[i:])
    return '.'.join(nodes)


class ProtobufFieldsWalker:
    def __init__(self, stream):
        self._stream = stream
        self._size = -1

    def get_size(self):
        return self._size

    def walk(self):
        offset = 0
        while offset < len(self._stream):
            tag = self._stream[offset]
            offset += 1
            wire_type = tag & 0x7
            if wire_type == 0:
                value, size = decode_varint128(self._stream[offset:])
                offset += size
            elif wire_type == 1:
                offset += 8
            elif wire_type == 2:
                value, size = decode_varint128(self._stream[offset:])
                offset += size + value
            elif wire_type == 5:
                offset += 4
            elif wire_type in (3, 4):
                continue
            else:
                break
        self._size = offset - 1


class FileDescriptorDisassembler:
    def __init__(self, file_desc):
        self.desc = file_desc

    def getLabel(self, l):
        return [None, 'optional', 'required', 'repeated'][l]

    def getTypeStr(self, t):
        types = [
            None, 'double', 'float', 'int64', 'uint64', 'int32', 'fixed64', 'fixed32',
            'bool', 'string', 'group', 'message', 'bytes', 'uint32', 'enum',
            'sfixed32', 'sfixed64', 'sint32', 'sint64'
        ]
        return types[t]

    def renderEnum(self, enum, depth=0, package='', nested=False):
        buffer = '\n' + ' ' * depth + f'enum {enum.name} {{\n'
        for value in enum.value:
            buffer += ' ' * (depth + 1) + f'{value.name} = {value.number};\n'
        buffer += ' ' * depth + '}\n'
        return buffer

    def renderField(self, field, depth=0, package='', nested=False):
        buffer = ''
        try:
            if field.HasField('type'):
                if field.type in (FieldDescriptorProto.TYPE_MESSAGE, FieldDescriptorProto.TYPE_ENUM):
                    field.type_name = render_type(field.type_name[1:], package)
                    buffer += ' ' * depth + f'{self.getLabel(field.label)} {field.type_name} {field.name} = {field.number};\n'
                else:
                    if field.HasField('default_value'):
                        default_val = f'"{field.default_value}"' if self.getTypeStr(field.type) == 'string' else field.default_value
                        buffer += ' ' * depth + f'{self.getLabel(field.label)} {self.getTypeStr(field.type)} {field.name} = {field.number} [default = {default_val}];\n'
                    else:
                        buffer += ' ' * depth + f'{self.getLabel(field.label)} {self.getTypeStr(field.type)} {field.name} = {field.number};\n'
        except ValueError:
            buffer += ' ' * depth + f'message {field.name} {{\n'
            _package = package + '.' + field.name
            for nested in field.nested_type:
                buffer += self.renderField(nested, depth + 1, _package, nested=True)
            for enum in field.enum_type:
                buffer += self.renderEnum(enum, depth + 1, _package)
            for f in field.field:
                buffer += self.renderField(f, depth + 1, _package)
            buffer += ' ' * depth + '}\n\n'
        return buffer

    def render(self, filename=None):
        print(f'[+] Processing {self.desc.name}')
        buffer = f'package {self.desc.package};\n\n'
        for dependency in self.desc.dependency:
            buffer += f'import "{dependency}";\n'
        if self.desc.dependency:
            buffer += '\n'
        for enum in self.desc.enum_type:
            buffer += self.renderEnum(enum, package=self.desc.package)
        for message in self.desc.message_type:
            buffer += self.renderField(message, package=self.desc.package)
        path = filename or self.desc.name
        _dir = os.path.dirname(path)
        if _dir and not os.path.exists(_dir):
            os.makedirs(_dir)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(buffer)


class ProtobufExtractor:
    def __init__(self, filename=None):
        self.filename = filename

    def extract(self):
        try:
            with open(self.filename, 'rb') as f:
                content = f.read()
            protos = []
            stream = content
            while stream:
                try:
                    r = stream.index(b'.proto')
                    for j in range(64):
                        try:
                            if decode_varint128(stream[r - j:])[0] == (j + 5) and is_valid_filename(stream[r - j + 1:r + 6].decode('utf-8', errors='ignore')):
                                walker = ProtobufFieldsWalker(stream[r - j - 1:])
                                walker.walk()
                                probable_size = walker.get_size()
                                for k in range(probable_size + 1024, 0, -1):
                                    try:
                                        fds = FileDescriptorProto()
                                        fds.ParseFromString(stream[r - j - 1:r - j - 1 + k])
                                        protos.append(stream[r - j - 1:r - j - 1 + k])
                                        print(f'[i] Found protofile {stream[r - j + 1:r + 6].decode("utf-8", errors="ignore")} ({k} bytes)')
                                        break
                                    except (DecodeError, UnicodeDecodeError):
                                        pass
                                break
                        except IndexError:
                            pass
                    stream = stream[r + 6:]
                except ValueError:
                    break
            seen = []
            for content in protos:
                try:
                    fds = FileDescriptorProto()
                    fds.ParseFromString(content)
                    res = FileDescriptorDisassembler(fds)
                    if res.desc.name and res.desc.name not in seen:
                        with open(res.desc.name + '.protoc', 'wb') as f:
                            f.write(content)
                        res.render()
                        seen.append(res.desc.name)
                except DecodeError:
                    pass
        except IOError:
            print(f'[!] Unable to read {sys.argv[1]}')


if __name__ == '__main__':
    if len(sys.argv) >= 2:
        print(f"[i] Extracting from {sys.argv[1]} ...")
        extractor = ProtobufExtractor(sys.argv[1])
        extractor.extract()
        print("[i] Done")
    else:
        print("[ Protod (Protobuf metadata extractor) (c) 2012 Sysdream ]\n")
        print(f'[i] Usage: {sys.argv[0]} [executable]')
