# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sounds.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sounds_common_pb2 as sounds__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csounds.proto\x12\x14tibia.protobuf.sound\x1a\x13sounds-common.proto\"\xc4\x02\n\x06Sounds\x12*\n\x05sound\x18\x01 \x03(\x0b\x32\x1b.tibia.protobuf.sound.Sound\x12\x46\n\x14numeric_sound_effect\x18\x02 \x03(\x0b\x32(.tibia.protobuf.sound.NumericSoundEffect\x12=\n\x0f\x61mbience_stream\x18\x03 \x03(\x0b\x32$.tibia.protobuf.sound.AmbienceStream\x12J\n\x16\x61mbience_object_stream\x18\x04 \x03(\x0b\x32*.tibia.protobuf.sound.AmbienceObjectStream\x12;\n\x0emusic_template\x18\x05 \x03(\x0b\x32#.tibia.protobuf.sound.MusicTemplate\"S\n\x05Sound\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x19\n\x11original_filename\x18\x03 \x01(\t\x12\x11\n\tis_stream\x18\x04 \x01(\x08\"\xe4\x02\n\x12NumericSoundEffect\x12\n\n\x02id\x18\x01 \x01(\r\x12\x43\n\x12numeric_sound_type\x18\x02 \x01(\x0e\x32\'.tibia.protobuf.sound.ENumericSoundType\x12\x37\n\x0crandom_pitch\x18\x03 \x01(\x0b\x32!.tibia.protobuf.sound.MinMaxFloat\x12\x38\n\rrandom_volume\x18\x04 \x01(\x0b\x32!.tibia.protobuf.sound.MinMaxFloat\x12\x44\n\x13simple_sound_effect\x18\x05 \x01(\x0b\x32\'.tibia.protobuf.sound.SimpleSoundEffect\x12\x44\n\x13random_sound_effect\x18\x06 \x01(\x0b\x32\'.tibia.protobuf.sound.RandomSoundEffect\"y\n\x0e\x41mbienceStream\x12\n\n\x02id\x18\x01 \x01(\r\x12\x18\n\x10looping_sound_id\x18\x02 \x01(\r\x12\x41\n\x0f\x64\x65layed_effects\x18\x03 \x03(\x0b\x32(.tibia.protobuf.sound.DelayedSoundEffect\"\xae\x01\n\x14\x41mbienceObjectStream\x12\n\n\x02id\x18\x01 \x01(\r\x12 \n\x18\x63ounted_appearance_types\x18\x02 \x03(\r\x12L\n\rsound_effects\x18\x03 \x03(\x0b\x32\x35.tibia.protobuf.sound.AppearanceTypesCountSoundEffect\x12\x1a\n\x12max_sound_distance\x18\x04 \x01(\r\"c\n\rMusicTemplate\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08sound_id\x18\x02 \x01(\r\x12\x34\n\nmusic_type\x18\x03 \x01(\x0e\x32 .tibia.protobuf.sound.EMusicType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sounds_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOUNDS']._serialized_start=60
  _globals['_SOUNDS']._serialized_end=384
  _globals['_SOUND']._serialized_start=386
  _globals['_SOUND']._serialized_end=469
  _globals['_NUMERICSOUNDEFFECT']._serialized_start=472
  _globals['_NUMERICSOUNDEFFECT']._serialized_end=828
  _globals['_AMBIENCESTREAM']._serialized_start=830
  _globals['_AMBIENCESTREAM']._serialized_end=951
  _globals['_AMBIENCEOBJECTSTREAM']._serialized_start=954
  _globals['_AMBIENCEOBJECTSTREAM']._serialized_end=1128
  _globals['_MUSICTEMPLATE']._serialized_start=1130
  _globals['_MUSICTEMPLATE']._serialized_end=1229
# @@protoc_insertion_point(module_scope)
